[versions]
kotlin = "2.0.20"
changelog = "2.2.1"
intellij = "2.1.0"

# libraries
#junit = "4.13.2"

[libraries]
#junit = { group = "junit", name = "junit", version.ref = "junit" }

# https://github.com/JetBrains/kotlin
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# https://github.com/JetBrains/gradle-changelog-plugin
gradle-changelog = { module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version.ref = "changelog" }
# https://github.com/JetBrains/intellij-platform-gradle-plugin
gradle-intellij = { module = "org.jetbrains.intellij.platform:intellij-platform-gradle-plugin", version.ref = "intellij" }

[bundles]
build-plugins = ["gradle-kotlin", "gradle-changelog", "gradle-intellij"]
